//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvyUpdate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvyUpdate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA Updater Application..
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to install the new version. Please enable logging in the settings and report the issue on GitHub!.
        /// </summary>
        public static string error_installing {
            get {
                return ResourceManager.GetString("error_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit EnvyUpdate?.
        /// </summary>
        public static string exit_confirm {
            get {
                return ResourceManager.GetString("exit_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem downloading the driver installer. Please try again..
        /// </summary>
        public static string info_download_error {
            get {
                return ResourceManager.GetString("info_download_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading.
        /// </summary>
        public static string info_download_error_title {
            get {
                return ResourceManager.GetString("info_download_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver installer successfully downloaded..
        /// </summary>
        public static string info_download_success {
            get {
                return ResourceManager.GetString("info_download_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download successful.
        /// </summary>
        public static string info_download_success_title {
            get {
                return ResourceManager.GetString("info_download_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver files have finished extracting..
        /// </summary>
        public static string info_extract_complete {
            get {
                return ResourceManager.GetString("info_extract_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction complete.
        /// </summary>
        public static string info_extract_complete_title {
            get {
                return ResourceManager.GetString("info_extract_complete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver files are being extracted. This could take a few minutes..
        /// </summary>
        public static string info_extracting {
            get {
                return ResourceManager.GetString("info_extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting driver files.
        /// </summary>
        public static string info_extracting_title {
            get {
                return ResourceManager.GetString("info_extracting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the new driver version was completed..
        /// </summary>
        public static string info_install_complete {
            get {
                return ResourceManager.GetString("info_install_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update finished.
        /// </summary>
        public static string info_install_complete_title {
            get {
                return ResourceManager.GetString("info_install_complete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference reset..
        /// </summary>
        public static string info_reset_caption {
            get {
                return ResourceManager.GetString("info_reset_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference reset.\nEnvyUpdate will ask for computer form factor the next time it is started..
        /// </summary>
        public static string info_reset_message {
            get {
                return ResourceManager.GetString("info_reset_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running..
        /// </summary>
        public static string instance_already_running {
            get {
                return ResourceManager.GetString("instance_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of EnvyUpdate found. Application will restart.\nThis will probably take a few seconds..
        /// </summary>
        public static string message_new_version {
            get {
                return ResourceManager.GetString("message_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No NVIDIA GPU found. Application will exit..
        /// </summary>
        public static string no_compatible_gpu {
            get {
                return ResourceManager.GetString("no_compatible_gpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version was skipped. Update popups will be disabled until a new version releases..
        /// </summary>
        public static string skip_confirm {
            get {
                return ResourceManager.GetString("skip_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Windows startup.
        /// </summary>
        public static string ui_autostart {
            get {
                return ResourceManager.GetString("ui_autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging to file.
        /// </summary>
        public static string ui_enable_logging {
            get {
                return ResourceManager.GetString("ui_enable_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ui_home {
            get {
                return ResourceManager.GetString("ui_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCH driver.
        /// </summary>
        public static string ui_info_dch {
            get {
                return ResourceManager.GetString("ui_info_dch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile GPU (Laptop, etc)?.
        /// </summary>
        public static string ui_info_mobile {
            get {
                return ResourceManager.GetString("ui_info_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available..
        /// </summary>
        public static string ui_info_outdated {
            get {
                return ResourceManager.GetString("ui_info_outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date..
        /// </summary>
        public static string ui_info_uptodate {
            get {
                return ResourceManager.GetString("ui_info_uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvyUpdate website.
        /// </summary>
        public static string ui_info_website {
            get {
                return ResourceManager.GetString("ui_info_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ui_install {
            get {
                return ResourceManager.GetString("ui_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string ui_licenses {
            get {
                return ResourceManager.GetString("ui_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local driver version:.
        /// </summary>
        public static string ui_localdriver {
            get {
                return ResourceManager.GetString("ui_localdriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local driver type:.
        /// </summary>
        public static string ui_localdriver_type {
            get {
                return ResourceManager.GetString("ui_localdriver_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All good..
        /// </summary>
        public static string ui_message_good {
            get {
                return ResourceManager.GetString("ui_message_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New driver found..
        /// </summary>
        public static string ui_message_update {
            get {
                return ResourceManager.GetString("ui_message_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online driver version:.
        /// </summary>
        public static string ui_onlinedriver {
            get {
                return ResourceManager.GetString("ui_onlinedriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open website.
        /// </summary>
        public static string ui_openwebsite {
            get {
                return ResourceManager.GetString("ui_openwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ui_settings {
            get {
                return ResourceManager.GetString("ui_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version skipped.
        /// </summary>
        public static string ui_skipped {
            get {
                return ResourceManager.GetString("ui_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string ui_skipversion {
            get {
                return ResourceManager.GetString("ui_skipversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio Driver is not supported by this graphics card..
        /// </summary>
        public static string ui_studionotsupported {
            get {
                return ResourceManager.GetString("ui_studionotsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall EnvyUpdate?.
        /// </summary>
        public static string uninstall_confirm {
            get {
                return ResourceManager.GetString("uninstall_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall?.
        /// </summary>
        public static string uninstall_heading {
            get {
                return ResourceManager.GetString("uninstall_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvyUpdate must be uninstalled because of an application bug. Please download the most recent version again..
        /// </summary>
        public static string uninstall_legacy_message {
            get {
                return ResourceManager.GetString("uninstall_legacy_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your operating system is not supported by EnvyUpdate. Windows 10 or later is required..
        /// </summary>
        public static string unsupported_os {
            get {
                return ResourceManager.GetString("unsupported_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new driver update is available for your graphics card..
        /// </summary>
        public static string update_popup_message {
            get {
                return ResourceManager.GetString("update_popup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
